#Copied from https://github.com/osherson/B2GAnalysis_2020/blob/master/analysis/CombineStep1.py
#And modified for my analysis
import ROOT
from ROOT import *
import numpy
import math
import sys
import array
import os
#import TEMPPAYLOAD
#from TEMPPAYLOAD import *

def GoodPlotFormat(H, *args): # Handy little script for color/line/fill/point/etc...
	try: H.SetStats(0)
	except: print " ------------ [  No stats box found!  ]"
	if args[0] == 'thickline':
		H.SetLineColor(args[1])
		H.SetLineWidth(2)
	if args[0] == 'thinline':
		H.SetLineColor(args[1])
		H.SetLineWidth(1)
		H.SetLineStyle(args[2])
	if args[0] == 'fill':
		H.SetLineColor(args[1])
		H.SetFillColor(args[1])
		H.SetFillStyle(args[2])
	if args[0] == 'markers':
		H.SetLineColor(args[1])
		H.SetMarkerColor(args[1])
		H.SetMarkerStyle(args[2])
	H.GetXaxis().SetTitleSize(0.04)

	if args[0] == 'dashed':
		H.SetLineColor(args[1])
		H.SetLineWidth(1)
		H.SetLineStyle(7)


def FindAndSetMax(*args):
	if len(args) == 1: args = args[0]
	maximum = 0.0
	for i in args:
		i.SetStats(0)
		t = i.GetMaximum()
		if t > maximum:
			maximum = t
	for j in args:
		j.GetYaxis().SetRangeUser(1,maximum*1.35)#should be 1.35 (below as well)
		j.SetLineWidth(2)
	return maximum*1.35

def AddCMSLumi(pad, fb, extra):
	cmsText     = "CMS " + extra
	cmsTextFont   = 61  
	lumiTextSize     = 0.45
	lumiTextOffset   = 0.15
	cmsTextSize      = 0.5
	cmsTextOffset    = 0.15
	H = pad.GetWh()
	W = pad.GetWw()
	l = pad.GetLeftMargin()
	t = pad.GetTopMargin()
	r = pad.GetRightMargin()
	b = pad.GetBottomMargin()
	e = 0.025
	pad.cd()
	lumiText = str(fb)+" fb^{-1} (13 TeV)"
	latex = TLatex()
	latex.SetNDC()
	latex.SetTextAngle(0)
	latex.SetTextColor(kBlack)	
	extraTextSize = 0.76*cmsTextSize
	latex.SetTextFont(42)
	latex.SetTextAlign(31) 
	latex.SetTextSize(lumiTextSize*t)	
	latex.DrawLatex(1-r,1-t+lumiTextOffset*t,lumiText)
	pad.cd()
	latex.SetTextFont(cmsTextFont)
	latex.SetTextSize(cmsTextSize*t)
	latex.SetTextAlign(11)
	#latex.DrawLatex(0.1265, 0.825, cmsText)
	latex.DrawLatex(0.185, 0.825, cmsText)
	pad.Update()


def pTbin(pad, Bin):
	cmsText     = "pT Bin: "+Bin+" GeV"
	cmsTextFont   = 61  
	cmsTextSize      = 0.5
	cmsTextOffset    = 0.15
	H = pad.GetWh()
	W = pad.GetWw()
	l = pad.GetLeftMargin()
	t = pad.GetTopMargin()
	r = pad.GetRightMargin()
	b = pad.GetBottomMargin()
	e = 0.025
	pad.cd()
	latex = TLatex()
	latex.SetNDC()
	latex.SetTextAngle(0)
	latex.SetTextColor(kBlack)	
	extraTextSize = 0.76*cmsTextSize
	pad.cd()
	latex.SetTextFont(cmsTextFont)
	latex.SetTextSize(cmsTextSize*t)
	latex.SetTextAlign(11)
	latex.DrawLatex(0.63, 0.6, cmsText)
	pad.Update()

def convertBinNHist(H, template, name):
	Hist = template.Clone(name)
	for i in range(1,Hist.GetNbinsX()+1):
		Hist.SetBinContent(i,H.GetBinContent(i))
		if H.GetBinContent(i) > 0 and (name == "dataprefitnewprefit" or name == "datafit_bnewfit_b" or name == "datafit_snewfit_s"):
	                Hist.SetBinError(i,math.sqrt(H.GetBinContent(i)))
		else:
			Hist.SetBinError(i,H.GetBinError(i))
	return Hist

def drawMorph(name, ifile1):
	gROOT.SetBatch(True)
	ptBins = [220, 260, 300, 360, 700]

	sig_name = "150GeV"
	sig_tag = "Sig150"

	Blind = True
	LUMI = 4.148 #Temporary luminosity with 10% of 2017 data
	cmsextra = "Preliminary"

	ttbar_nom_pass_total = TH1F("ttbar_nom_pass_total", "TTBar Nominal Pass Total", 40, 0, 200)
	ttbar_scaleUp_pass_total = TH1F("ttbar_scaleUp_pass_total", "TTBar ScaleUp Pass Total", 40, 0, 200)
	ttbar_scaleDown_pass_total = TH1F("ttbar_scaleDown_pass_total", "TTBar ScaleDown Pass Total", 40, 0, 200)
	ttbar_smearUp_pass_total = TH1F("ttbar_smearUp_pass_total", "TTBar SmearUp Pass Total", 40, 0, 200)
	ttbar_smearDown_pass_total = TH1F("ttbar_smearDown_pass_total", "TTBar SmearDown Pass Total", 40, 0, 200)
	ttbar_scaleUp_weights_pass_total = TH1F("ttbar_scaleUp_weights_pass_total", "TTBar ScaleUp Weights Pass Total", 40, 0, 200)
	ttbar_scaleDown_weights_pass_total = TH1F("ttbar_scaleDown_weights_pass_total", "TTBar ScaleDown Weights Pass Total", 40, 0, 200)
	ttbar_smearUp_weights_pass_total = TH1F("ttbar_smearUp_weights_pass_total", "TTBar SmearUp Weights Pass Total", 40, 0, 200)
	ttbar_smearDown_weights_pass_total = TH1F("ttbar_smearDown_weights_pass_total", "TTBar SmearDown Weights Pass Total", 40, 0, 200)

	sig_nom_pass_total = TH1F("sig_nom_pass_total", sig_name+" Signal Nominal Pass Total", 40, 0, 200)
	sig_scaleUp_pass_total = TH1F("sig_scaleUp_pass_total", sig_name+" Signal ScaleUp Pass Total", 40, 0, 200)
	sig_scaleDown_pass_total = TH1F("sig_scaleDown_pass_total", sig_name+" Signal ScaleDown Pass Total", 40, 0, 200)
	sig_smearUp_pass_total = TH1F("sig_smearUp_pass_total", sig_name+" Signal SmearUp Pass Total", 40, 0, 200)
	sig_smearDown_pass_total = TH1F("sig_smearDown_pass_total", sig_name+" Signal SmearDown Pass Total", 40, 0, 200)
	sig_scaleUp_weights_pass_total = TH1F("sig_scaleUp_weights_pass_total", "Signal ScaleUp Weights Pass Total", 40, 0, 200)
	sig_scaleDown_weights_pass_total = TH1F("sig_scaleDown_weights_pass_total", "Signal ScaleDown Weights Pass Total", 40, 0, 200)
	sig_smearUp_weights_pass_total = TH1F("sig_smearUp_weights_pass_total", "Signal SmearUp Weights Pass Total", 40, 0, 200)
	sig_smearDown_weights_pass_total = TH1F("sig_smearDown_weights_pass_total", "Signal SmearDown Weights Pass Total", 40, 0, 200)

	wgamma_nom_pass_total = TH1F("wgamma_nom_pass_total", "WGamma Nominal Pass Total", 40, 0, 200)
	wgamma_scaleUp_pass_total = TH1F("wgamma_scaleUp_pass_total", "WGamma ScaleUp Pass Total", 40, 0, 200)
	wgamma_scaleDown_pass_total = TH1F("wgamma_scaleDown_pass_total", "WGamma ScaleDown Pass Total", 40, 0, 200)
	wgamma_smearUp_pass_total = TH1F("wgamma_smearUp_pass_total", "WGamma SmearUp Pass Total", 40, 0, 200)
	wgamma_smearDown_pass_total = TH1F("wgamma_smearDown_pass_total", "WGamma SmearDown Pass Total", 40, 0, 200)
	wgamma_scaleUp_weights_pass_total = TH1F("wgamma_scaleUp_weights_pass_total", "WGamma ScaleUp Weights Pass Total", 40, 0, 200)
	wgamma_scaleDown_weights_pass_total = TH1F("wgamma_scaleDown_weights_pass_total", "WGamma ScaleDown Weights Pass Total", 40, 0, 200)
	wgamma_smearUp_weights_pass_total = TH1F("wgamma_smearUp_weights_pass_total", "WGamma SmearUp Weights Pass Total", 40, 0, 200)
	wgamma_smearDown_weights_pass_total = TH1F("wgamma_smearDown_weights_pass_total", "WGamma SmearDown Weights Pass Total", 40, 0, 200)
	
	zgamma_nom_pass_total = TH1F("zgamma_nom_pass_total", "ZGamma Nominal Pass Total", 40, 0, 200)
	zgamma_scaleUp_pass_total = TH1F("zgamma_scaleUp_pass_total", "ZGamma ScaleUp Pass Total", 40, 0, 200)
	zgamma_scaleDown_pass_total = TH1F("zgamma_scaleDown_pass_total", "ZGamma ScaleDown Pass Total", 40, 0, 200)
	zgamma_smearUp_pass_total = TH1F("zgamma_smearUp_pass_total", "ZGamma SmearUp Pass Total", 40, 0, 200)
	zgamma_smearDown_pass_total = TH1F("zgamma_smearDown_pass_total", "ZGamma SmearDown Pass Total", 40, 0, 200)
	zgamma_scaleUp_weights_pass_total = TH1F("zgamma_scaleUp_weights_pass_total", "ZGamma ScaleUp Weights Pass Total", 40, 0, 200)
	zgamma_scaleDown_weights_pass_total = TH1F("zgamma_scaleDown_weights_pass_total", "ZGamma ScaleDown Weights Pass Total", 40, 0, 200)
	zgamma_smearUp_weights_pass_total = TH1F("zgamma_smearUp_weights_pass_total", "ZGamma SmearUp Weights Pass Total", 40, 0, 200)
	zgamma_smearDown_weights_pass_total = TH1F("zgamma_smearDown_weights_pass_total", "ZGamma SmearDown Weights Pass Total", 40, 0, 200)
	
	ttbar_nom_fail_total = TH1F("ttbar_nom_fail_total", "TTBar Nominal Fail Total", 40, 0, 200)
	ttbar_scaleUp_fail_total = TH1F("ttbar_scaleUp_fail_total", "TTBar ScaleUp Fail Total", 40, 0, 200)
	ttbar_scaleDown_fail_total = TH1F("ttbar_scaleDown_fail_total", "TTBar ScaleDown Fail Total", 40, 0, 200)
	ttbar_smearUp_fail_total = TH1F("ttbar_smearUp_fail_total", "TTBar SmearUp Fail Total", 40, 0, 200)
	ttbar_smearDown_fail_total = TH1F("ttbar_smearDown_fail_total", "TTBar SmearDown Fail Total", 40, 0, 200)
	ttbar_scaleUp_weights_fail_total = TH1F("ttbar_scaleUp_weights_fail_total", "TTBar ScaleUp Weights Fail Total", 40, 0, 200)
	ttbar_scaleDown_weights_fail_total = TH1F("ttbar_scaleDown_weights_fail_total", "TTBar ScaleDown Weights Fail Total", 40, 0, 200)
	ttbar_smearUp_weights_fail_total = TH1F("ttbar_smearUp_weights_fail_total", "TTBar SmearUp Weights Fail Total", 40, 0, 200)
	ttbar_smearDown_weights_fail_total = TH1F("ttbar_smearDown_weights_fail_total", "TTBar SmearDown Weights Fail Total", 40, 0, 200)

	sig_nom_fail_total = TH1F("sig_nom_fail_total", sig_name+" Signal Nominal Fail Total", 40, 0, 200)
	sig_scaleUp_fail_total = TH1F("sig_scaleUp_fail_total", sig_name+" Signal ScaleUp Fail Total", 40, 0, 200)
	sig_scaleDown_fail_total = TH1F("sig_scaleDown_fail_total", sig_name+" Signal ScaleDown Fail Total", 40, 0, 200)
	sig_smearUp_fail_total = TH1F("sig_smearUp_fail_total", sig_name+" Signal SmearUp Fail Total", 40, 0, 200)
	sig_smearDown_fail_total = TH1F("sig_smearDown_fail_total", sig_name+" Signal SmearDown Fail Total", 40, 0, 200)
	sig_scaleUp_weights_fail_total = TH1F("sig_scaleUp_weights_fail_total", "Signal ScaleUp Weights Fail Total", 40, 0, 200)
	sig_scaleDown_weights_fail_total = TH1F("sig_scaleDown_weights_fail_total", "Signal ScaleDown Weights Fail Total", 40, 0, 200)
	sig_smearUp_weights_fail_total = TH1F("sig_smearUp_weights_fail_total", "Signal SmearUp Weights Fail Total", 40, 0, 200)
	sig_smearDown_weights_fail_total = TH1F("sig_smearDown_weights_fail_total", "Signal SmearDown Weights Fail Total", 40, 0, 200)

	wgamma_nom_fail_total = TH1F("wgamma_nom_fail_total", "WGamma Nominal Fail Total", 40, 0, 200)
	wgamma_scaleUp_fail_total = TH1F("wgamma_scaleUp_fail_total", "WGamma ScaleUp Fail Total", 40, 0, 200)
	wgamma_scaleDown_fail_total = TH1F("wgamma_scaleDown_fail_total", "WGamma ScaleDown Fail Total", 40, 0, 200)
	wgamma_smearUp_fail_total = TH1F("wgamma_smearUp_fail_total", "WGamma SmearUp Fail Total", 40, 0, 200)
	wgamma_smearDown_fail_total = TH1F("wgamma_smearDown_fail_total", "WGamma SmearDown Fail Total", 40, 0, 200)
	wgamma_scaleUp_weights_fail_total = TH1F("wgamma_scaleUp_weights_fail_total", "WGamma ScaleUp Weights Fail Total", 40, 0, 200)
	wgamma_scaleDown_weights_fail_total = TH1F("wgamma_scaleDown_weights_fail_total", "WGamma ScaleDown Weights Fail Total", 40, 0, 200)
	wgamma_smearUp_weights_fail_total = TH1F("wgamma_smearUp_weights_fail_total", "WGamma SmearUp Weights Fail Total", 40, 0, 200)
	wgamma_smearDown_weights_fail_total = TH1F("wgamma_smearDown_weights_fail_total", "WGamma SmearDown Weights Fail Total", 40, 0, 200)
	
	zgamma_nom_fail_total = TH1F("zgamma_nom_fail_total", "ZGamma Nominal Fail Total", 40, 0, 200)
	zgamma_scaleUp_fail_total = TH1F("zgamma_scaleUp_fail_total", "ZGamma ScaleUp Fail Total", 40, 0, 200)
	zgamma_scaleDown_fail_total = TH1F("zgamma_scaleDown_fail_total", "ZGamma ScaleDown Fail Total", 40, 0, 200)
	zgamma_smearUp_fail_total = TH1F("zgamma_smearUp_fail_total", "ZGamma SmearUp Fail Total", 40, 0, 200)
	zgamma_smearDown_fail_total = TH1F("zgamma_smearDown_fail_total", "ZGamma SmearDown Fail Total", 40, 0, 200)
	zgamma_scaleUp_weights_fail_total = TH1F("zgamma_scaleUp_weights_fail_total", "ZGamma ScaleUp Weights Fail Total", 40, 0, 200)
	zgamma_scaleDown_weights_fail_total = TH1F("zgamma_scaleDown_weights_fail_total", "ZGamma ScaleDown Weights Fail Total", 40, 0, 200)
	zgamma_smearUp_weights_fail_total = TH1F("zgamma_smearUp_weights_fail_total", "ZGamma SmearUp Weights Fail Total", 40, 0, 200)
	zgamma_smearDown_weights_fail_total = TH1F("zgamma_smearDown_weights_fail_total", "ZGamma SmearDown Weights Fail Total", 40, 0, 200)

	save_name = ["ttbar", sig_tag, "wgamma", "zgamma"]
			
	titles = ["TTBar", sig_name, "WGamma", "ZGamma"]

	nbins = 5 #Number of pT Bins
	for pf in ["pass", "fail"]:
		for a in range(0, nbins):
			print("ptbin #"+str(a))
			NAME = "ptbin"+str(a)+pf
			refF = ROOT.TFile("FitHist.root")
			refH = refF.Get("Data_"+pf+"_soft")
			
			CbnF = ROOT.TFile(ifile1)
			cTT_nom = CbnF.Get("TTBar_nom_"+pf+str(a))
			cTT_scaleUp = CbnF.Get("TTBar_scaleUp_"+pf+str(a))
			cTT_scaleDown = CbnF.Get("TTBar_scaleDown_"+pf+str(a))
			cTT_smearUp = CbnF.Get("TTBar_smearUp_"+pf+str(a))
			cTT_smearDown = CbnF.Get("TTBar_smearDown_"+pf+str(a))
			cTT_scaleUp_weights = CbnF.Get("TTBar_scaleUp_weights_"+pf+str(a))
			cTT_scaleDown_weights = CbnF.Get("TTBar_scaleDown_weights_"+pf+str(a))
			cTT_smearUp_weights = CbnF.Get("TTBar_smearUp_weights_"+pf+str(a))
			cTT_smearDown_weights = CbnF.Get("TTBar_smearDown_weights_"+pf+str(a))
			cSIG_nom = CbnF.Get(sig_tag+"_nom_"+pf+str(a))
			cSIG_scaleUp = CbnF.Get(sig_tag+"_scaleUp_"+pf+str(a))
			cSIG_scaleDown = CbnF.Get(sig_tag+"_scaleDown_"+pf+str(a))
			cSIG_smearUp = CbnF.Get(sig_tag+"_smearUp_"+pf+str(a))
			cSIG_smearDown = CbnF.Get(sig_tag+"_smearDown_"+pf+str(a))
			cSIG_scaleUp_weights = CbnF.Get(sig_tag+"_scaleUp_weights_"+pf+str(a))
			cSIG_scaleDown_weights = CbnF.Get(sig_tag+"_scaleDown_weights_"+pf+str(a))
			cSIG_smearUp_weights = CbnF.Get(sig_tag+"_smearUp_weights_"+pf+str(a))
			cSIG_smearDown_weights = CbnF.Get(sig_tag+"_smearDown_weights_"+pf+str(a))
			cWG_nom = CbnF.Get("WGamma_nom_"+pf+str(a))
			cWG_scaleUp = CbnF.Get("WGamma_scaleUp_"+pf+str(a))
			cWG_scaleDown = CbnF.Get("WGamma_scaleDown_"+pf+str(a))
			cWG_smearUp = CbnF.Get("WGamma_smearUp_"+pf+str(a))
			cWG_smearDown = CbnF.Get("WGamma_smearDown_"+pf+str(a))
			cWG_scaleUp_weights = CbnF.Get("WGamma_scaleUp_weights_"+pf+str(a))
			cWG_scaleDown_weights = CbnF.Get("WGamma_scaleDown_weights_"+pf+str(a))
			cWG_smearUp_weights = CbnF.Get("WGamma_smearUp_weights_"+pf+str(a))
			cWG_smearDown_weights = CbnF.Get("WGamma_smearDown_weights_"+pf+str(a))
			cZG_nom = CbnF.Get("ZGamma_nom_"+pf+str(a))
			cZG_scaleUp = CbnF.Get("ZGamma_scaleUp_"+pf+str(a))
			cZG_scaleDown = CbnF.Get("ZGamma_scaleDown_"+pf+str(a))
			cZG_smearUp = CbnF.Get("ZGamma_smearUp_"+pf+str(a))
			cZG_smearDown = CbnF.Get("ZGamma_smearDown_"+pf+str(a))
			cZG_scaleUp_weights = CbnF.Get("ZGamma_scaleUp_weights_"+pf+str(a))
			cZG_scaleDown_weights = CbnF.Get("ZGamma_scaleDown_weights_"+pf+str(a))
			cZG_smearUp_weights = CbnF.Get("ZGamma_smearUp_weights_"+pf+str(a))
			cZG_smearDown_weights = CbnF.Get("ZGamma_smearDown_weights_"+pf+str(a))

			#cTT_nom = convertBinNHist(cTT_nom, refH, cTT_nom.GetName()+"new")
			
			GoodPlotFormat(cTT_nom, "thinline", ROOT.kBlack, 1)
			GoodPlotFormat(cTT_scaleUp, "dashed", ROOT.kBlue, 1)
			GoodPlotFormat(cTT_scaleDown, "dashed", ROOT.kRed, 1)
			GoodPlotFormat(cTT_smearUp, "dashed", ROOT.kBlue, 1)
			GoodPlotFormat(cTT_smearDown, "dashed", ROOT.kRed, 1)
			GoodPlotFormat(cSIG_nom, "thinline", ROOT.kBlack, 1)
			GoodPlotFormat(cSIG_scaleUp, "dashed", ROOT.kBlue, 1)
			GoodPlotFormat(cSIG_scaleDown, "dashed", ROOT.kRed, 1)
			GoodPlotFormat(cSIG_smearUp, "dashed", ROOT.kBlue, 1)
			GoodPlotFormat(cSIG_smearDown, "dashed", ROOT.kRed, 1)
			GoodPlotFormat(cWG_nom, "thinline", ROOT.kBlack, 1)
			GoodPlotFormat(cWG_scaleUp, "dashed", ROOT.kBlue, 1)
			GoodPlotFormat(cWG_scaleDown, "dashed", ROOT.kRed, 1)
			GoodPlotFormat(cWG_smearUp, "dashed", ROOT.kBlue, 1)
			GoodPlotFormat(cWG_smearDown, "dashed", ROOT.kRed, 1)
			GoodPlotFormat(cZG_nom, "thinline", ROOT.kBlack, 1)
			GoodPlotFormat(cZG_scaleUp, "dashed", ROOT.kBlue, 1)
			GoodPlotFormat(cZG_scaleDown, "dashed", ROOT.kRed, 1)
			GoodPlotFormat(cZG_smearUp, "dashed", ROOT.kBlue, 1)
			GoodPlotFormat(cZG_smearDown, "dashed", ROOT.kRed, 1)

			FindAndSetMax(cTT_nom, cTT_scaleUp, cTT_scaleDown, cTT_smearUp, cTT_smearDown)
			FindAndSetMax(cSIG_nom, cSIG_scaleUp, cSIG_scaleDown, cSIG_smearUp, cSIG_smearDown)
			FindAndSetMax(cWG_nom, cWG_scaleUp, cWG_scaleDown, cWG_smearUp, cWG_smearDown)
			FindAndSetMax(cZG_nom, cZG_scaleUp, cZG_scaleDown, cZG_smearUp, cZG_smearDown)

			HVec = [[cTT_nom, cTT_scaleUp, cTT_scaleDown, cTT_smearUp, cTT_smearDown], [cSIG_nom, cSIG_scaleUp, cSIG_scaleDown, cSIG_smearUp, cSIG_smearDown], [cWG_nom, cWG_scaleUp, cWG_scaleDown, cWG_smearUp, cWG_smearDown], [cZG_nom, cZG_scaleUp, cZG_scaleDown, cZG_smearUp, cZG_smearDown]]
	
			# If sample nom value is zero, set weight to 1
			nom_weights = TLine(0,1,200,1)
			nom_weights.SetLineColor(ROOT.kBlack)
			nom_weights.SetLineStyle(1)
	
			HVec_weights = [[nom_weights, cTT_scaleUp_weights, cTT_scaleDown_weights, cTT_smearUp_weights, cTT_smearDown_weights], [nom_weights, cSIG_scaleUp_weights, cSIG_scaleDown_weights, cSIG_smearUp_weights, cSIG_smearDown_weights],[nom_weights, cWG_scaleUp_weights, cWG_scaleDown_weights, cWG_smearUp_weights, cWG_smearDown_weights],[nom_weights, cZG_scaleUp_weights, cZG_scaleDown_weights, cZG_smearUp_weights, cZG_smearDown_weights]]
			for i in range(0, 4):
				for j in range(1, 5):
					for k in range(1, HVec[i][0].GetNbinsX()+1):
						if HVec[i][0].GetBinContent(k) < 0.00001:
							HVec_weights[i][j].SetBinContent(k, 1)

			if pf == "pass":
				ttbar_nom_pass_total.Add(cTT_nom)						
				ttbar_scaleUp_pass_total.Add(cTT_scaleUp)						
				ttbar_scaleDown_pass_total.Add(cTT_scaleDown)						
				ttbar_smearUp_pass_total.Add(cTT_smearUp)						
				ttbar_smearDown_pass_total.Add(cTT_smearDown)
				ttbar_scaleUp_weights_pass_total.Add(cTT_scaleUp_weights)						
				ttbar_scaleDown_weights_pass_total.Add(cTT_scaleDown_weights)						
				ttbar_smearUp_weights_pass_total.Add(cTT_smearUp_weights)						
				ttbar_smearDown_weights_pass_total.Add(cTT_smearDown_weights)
				sig_nom_pass_total.Add(cSIG_nom)						
				sig_scaleUp_pass_total.Add(cSIG_scaleUp)						
				sig_scaleDown_pass_total.Add(cSIG_scaleDown)						
				sig_smearUp_pass_total.Add(cSIG_smearUp)						
				sig_smearDown_pass_total.Add(cSIG_smearDown)
				sig_scaleUp_weights_pass_total.Add(cSIG_scaleUp_weights)						
				sig_scaleDown_weights_pass_total.Add(cSIG_scaleDown_weights)						
				sig_smearUp_weights_pass_total.Add(cSIG_smearUp_weights)						
				sig_smearDown_weights_pass_total.Add(cSIG_smearDown_weights)
				wgamma_nom_pass_total.Add(cWG_nom)						
				wgamma_scaleUp_pass_total.Add(cWG_scaleUp)						
				wgamma_scaleDown_pass_total.Add(cWG_scaleDown)						
				wgamma_smearUp_pass_total.Add(cWG_smearUp)						
				wgamma_smearDown_pass_total.Add(cWG_smearDown)
				wgamma_scaleUp_weights_pass_total.Add(cWG_scaleUp_weights)						
				wgamma_scaleDown_weights_pass_total.Add(cWG_scaleDown_weights)						
				wgamma_smearUp_weights_pass_total.Add(cWG_smearUp_weights)						
				wgamma_smearDown_weights_pass_total.Add(cWG_smearDown_weights)
				zgamma_nom_pass_total.Add(cZG_nom)						
				zgamma_scaleUp_pass_total.Add(cZG_scaleUp)						
				zgamma_scaleDown_pass_total.Add(cZG_scaleDown)						
				zgamma_smearUp_pass_total.Add(cZG_smearUp)						
				zgamma_smearDown_pass_total.Add(cZG_smearDown)
				zgamma_scaleUp_weights_pass_total.Add(cZG_scaleUp_weights)						
				zgamma_scaleDown_weights_pass_total.Add(cZG_scaleDown_weights)						
				zgamma_smearUp_weights_pass_total.Add(cZG_smearUp_weights)						
				zgamma_smearDown_weights_pass_total.Add(cZG_smearDown_weights)
			else:
				ttbar_nom_fail_total.Add(cTT_nom)						
				ttbar_scaleUp_fail_total.Add(cTT_scaleUp)						
				ttbar_scaleDown_fail_total.Add(cTT_scaleDown)						
				ttbar_smearUp_fail_total.Add(cTT_smearUp)						
				ttbar_smearDown_fail_total.Add(cTT_smearDown)
				ttbar_scaleUp_weights_fail_total.Add(cTT_scaleUp_weights)						
				ttbar_scaleDown_weights_fail_total.Add(cTT_scaleDown_weights)						
				ttbar_smearUp_weights_fail_total.Add(cTT_smearUp_weights)						
				ttbar_smearDown_weights_fail_total.Add(cTT_smearDown_weights)
				sig_nom_fail_total.Add(cSIG_nom)						
				sig_scaleUp_fail_total.Add(cSIG_scaleUp)						
				sig_scaleDown_fail_total.Add(cSIG_scaleDown)						
				sig_smearUp_fail_total.Add(cSIG_smearUp)						
				sig_smearDown_fail_total.Add(cSIG_smearDown)
				sig_scaleUp_weights_fail_total.Add(cSIG_scaleUp_weights)						
				sig_scaleDown_weights_fail_total.Add(cSIG_scaleDown_weights)						
				sig_smearUp_weights_fail_total.Add(cSIG_smearUp_weights)						
				sig_smearDown_weights_fail_total.Add(cSIG_smearDown_weights)
				wgamma_nom_fail_total.Add(cWG_nom)						
				wgamma_scaleUp_fail_total.Add(cWG_scaleUp)						
				wgamma_scaleDown_fail_total.Add(cWG_scaleDown)						
				wgamma_smearUp_fail_total.Add(cWG_smearUp)						
				wgamma_smearDown_fail_total.Add(cWG_smearDown)
				wgamma_scaleUp_weights_fail_total.Add(cWG_scaleUp_weights)						
				wgamma_scaleDown_weights_fail_total.Add(cWG_scaleDown_weights)						
				wgamma_smearUp_weights_fail_total.Add(cWG_smearUp_weights)						
				wgamma_smearDown_weights_fail_total.Add(cWG_smearDown_weights)
				zgamma_nom_fail_total.Add(cZG_nom)						
				zgamma_scaleUp_fail_total.Add(cZG_scaleUp)						
				zgamma_scaleDown_fail_total.Add(cZG_scaleDown)						
				zgamma_smearUp_fail_total.Add(cZG_smearUp)						
				zgamma_smearDown_fail_total.Add(cZG_smearDown)
				zgamma_scaleUp_weights_fail_total.Add(cZG_scaleUp_weights)						
				zgamma_scaleDown_weights_fail_total.Add(cZG_scaleDown_weights)						
				zgamma_smearUp_weights_fail_total.Add(cZG_smearUp_weights)						
				zgamma_smearDown_weights_fail_total.Add(cZG_smearDown_weights)
					


			for i in range(0,4):
				L = ROOT.TLegend(0.58,0.65,0.895,0.895)
				L.SetFillColor(0)
				L.SetLineColor(0)
				L.AddEntry(HVec[i][0], "Nominal")
				L.AddEntry(HVec[i][1], "ScaleUp")
				L.AddEntry(HVec[i][2], "ScaleDown")
				C = ROOT.TCanvas()
				C.cd()
				HVec[i][0].SetTitle(titles[i]+" Scale Morphing "+str(pf))
				HVec[i][0].Draw("hist")
				HVec[i][1].Draw("histsame")
				HVec[i][2].Draw("histsame")
				L.Draw("same")
				AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
				C.Print("morphing/ptbin"+str(a)+pf+"/"+save_name[i]+"_"+pf+str(a)+"_scaleMorph.png")
				C.Close()
			for i in range(0,4):
				L = ROOT.TLegend(0.58,0.65,0.895,0.895)
				L.SetFillColor(0)
				L.SetLineColor(0)
				L.AddEntry(HVec[i][0], "Nominal")
				L.AddEntry(HVec[i][3], "SmearUp")
				L.AddEntry(HVec[i][4], "SmearDown")
				C = ROOT.TCanvas()
				C.cd()
				HVec[i][0].SetTitle(titles[i]+" Smear Morphing "+str(pf))
				HVec[i][0].Draw("hist")
				HVec[i][3].Draw("histsame")
				HVec[i][4].Draw("histsame")
				L.Draw("same")
				AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
				C.Print("morphing/ptbin"+str(a)+pf+"/"+save_name[i]+"_"+pf+str(a)+"_smearMorph.png")
				C.Close()


	# Average the weights histograms over the pT bins
	ttbar_scaleUp_weights_pass_total.Scale(1.0/nbins)
	ttbar_scaleDown_weights_pass_total.Scale(1.0/nbins)
	ttbar_smearUp_weights_pass_total.Scale(1.0/nbins)
	ttbar_smearDown_weights_pass_total.Scale(1.0/nbins)
	sig_scaleUp_weights_pass_total.Scale(1.0/nbins)
	sig_scaleDown_weights_pass_total.Scale(1.0/nbins)
	sig_smearUp_weights_pass_total.Scale(1.0/nbins)
	sig_smearDown_weights_pass_total.Scale(1.0/nbins)
	wgamma_scaleUp_weights_pass_total.Scale(1.0/nbins)
	wgamma_scaleDown_weights_pass_total.Scale(1.0/nbins)
	wgamma_smearUp_weights_pass_total.Scale(1.0/nbins)
	wgamma_smearDown_weights_pass_total.Scale(1.0/nbins)
	zgamma_scaleUp_weights_pass_total.Scale(1.0/nbins)
	zgamma_scaleDown_weights_pass_total.Scale(1.0/nbins)
	zgamma_smearUp_weights_pass_total.Scale(1.0/nbins)
	zgamma_smearDown_weights_pass_total.Scale(1.0/nbins)
	
	ttbar_scaleUp_weights_fail_total.Scale(1.0/nbins)
	ttbar_scaleDown_weights_fail_total.Scale(1.0/nbins)
	ttbar_smearUp_weights_fail_total.Scale(1.0/nbins)
	ttbar_smearDown_weights_fail_total.Scale(1.0/nbins)
	sig_scaleUp_weights_fail_total.Scale(1.0/nbins)
	sig_scaleDown_weights_fail_total.Scale(1.0/nbins)
	sig_smearUp_weights_fail_total.Scale(1.0/nbins)
	sig_smearDown_weights_fail_total.Scale(1.0/nbins)
	wgamma_scaleUp_weights_fail_total.Scale(1.0/nbins)
	wgamma_scaleDown_weights_fail_total.Scale(1.0/nbins)
	wgamma_smearUp_weights_fail_total.Scale(1.0/nbins)
	wgamma_smearDown_weights_fail_total.Scale(1.0/nbins)
	zgamma_scaleUp_weights_fail_total.Scale(1.0/nbins)
	zgamma_scaleDown_weights_fail_total.Scale(1.0/nbins)
	zgamma_smearUp_weights_fail_total.Scale(1.0/nbins)
	zgamma_smearDown_weights_fail_total.Scale(1.0/nbins)

	FindAndSetMax(ttbar_nom_pass_total, ttbar_scaleUp_pass_total, ttbar_scaleDown_pass_total, ttbar_smearUp_pass_total, ttbar_smearDown_pass_total)
	FindAndSetMax(sig_nom_pass_total, sig_scaleUp_pass_total, sig_scaleDown_pass_total, sig_smearUp_pass_total, sig_smearDown_pass_total)
	FindAndSetMax(wgamma_nom_pass_total, wgamma_scaleUp_pass_total, wgamma_scaleDown_pass_total, wgamma_smearUp_pass_total, wgamma_smearDown_pass_total)
	FindAndSetMax(zgamma_nom_pass_total, zgamma_scaleUp_pass_total, zgamma_scaleDown_pass_total, zgamma_smearUp_pass_total, zgamma_smearDown_pass_total)
	FindAndSetMax(ttbar_nom_fail_total, ttbar_scaleUp_fail_total, ttbar_scaleDown_fail_total, ttbar_smearUp_fail_total, ttbar_smearDown_fail_total)
	FindAndSetMax(sig_nom_fail_total, sig_scaleUp_fail_total, sig_scaleDown_fail_total, sig_smearUp_fail_total, sig_smearDown_fail_total)
	FindAndSetMax(wgamma_nom_fail_total, wgamma_scaleUp_fail_total, wgamma_scaleDown_fail_total, wgamma_smearUp_fail_total, wgamma_smearDown_fail_total)
	FindAndSetMax(zgamma_nom_fail_total, zgamma_scaleUp_fail_total, zgamma_scaleDown_fail_total, zgamma_smearUp_fail_total, zgamma_smearDown_fail_total)

	ttbar_scaleUp_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	ttbar_scaleDown_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	ttbar_smearUp_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	ttbar_smearDown_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	sig_scaleUp_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	sig_scaleDown_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	sig_smearUp_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	sig_smearDown_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	wgamma_scaleUp_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	wgamma_scaleDown_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	wgamma_smearUp_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	wgamma_smearDown_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	zgamma_scaleUp_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	zgamma_scaleDown_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	zgamma_smearUp_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	zgamma_smearDown_weights_pass_total.GetYaxis().SetRangeUser(0.4,1.6)
	
	ttbar_scaleUp_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	ttbar_scaleDown_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	ttbar_smearUp_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	ttbar_smearDown_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	sig_scaleUp_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	sig_scaleDown_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	sig_smearUp_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	sig_smearDown_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	wgamma_scaleUp_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	wgamma_scaleDown_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	wgamma_smearUp_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	wgamma_smearDown_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	zgamma_scaleUp_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	zgamma_scaleDown_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	zgamma_smearUp_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)
	zgamma_smearDown_weights_fail_total.GetYaxis().SetRangeUser(0.4,1.6)

	
	GoodPlotFormat(ttbar_nom_pass_total, "thinline", ROOT.kBlack, 1)
	GoodPlotFormat(ttbar_scaleUp_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(ttbar_scaleDown_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(ttbar_smearUp_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(ttbar_smearDown_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(sig_nom_pass_total, "thinline", ROOT.kBlack, 1)
	GoodPlotFormat(sig_scaleUp_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(sig_scaleDown_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(sig_smearUp_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(sig_smearDown_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(wgamma_nom_pass_total, "thinline", ROOT.kBlack, 1)
	GoodPlotFormat(wgamma_scaleUp_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(wgamma_scaleDown_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(wgamma_smearUp_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(wgamma_smearDown_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(zgamma_nom_pass_total, "thinline", ROOT.kBlack, 1)
	GoodPlotFormat(zgamma_scaleUp_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(zgamma_scaleDown_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(zgamma_smearUp_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(zgamma_smearDown_pass_total, "dashed", ROOT.kRed, 1)

	GoodPlotFormat(ttbar_nom_fail_total, "thinline", ROOT.kBlack, 1)
	GoodPlotFormat(ttbar_scaleUp_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(ttbar_scaleDown_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(ttbar_smearUp_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(ttbar_smearDown_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(sig_nom_fail_total, "thinline", ROOT.kBlack, 1)
	GoodPlotFormat(sig_scaleUp_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(sig_scaleDown_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(sig_smearUp_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(sig_smearDown_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(wgamma_nom_fail_total, "thinline", ROOT.kBlack, 1)
	GoodPlotFormat(wgamma_scaleUp_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(wgamma_scaleDown_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(wgamma_smearUp_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(wgamma_smearDown_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(zgamma_nom_fail_total, "thinline", ROOT.kBlack, 1)
	GoodPlotFormat(zgamma_scaleUp_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(zgamma_scaleDown_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(zgamma_smearUp_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(zgamma_smearDown_fail_total, "dashed", ROOT.kRed, 1)

	GoodPlotFormat(ttbar_scaleUp_weights_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(ttbar_scaleDown_weights_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(ttbar_smearUp_weights_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(ttbar_smearDown_weights_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(sig_scaleUp_weights_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(sig_scaleDown_weights_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(sig_smearUp_weights_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(sig_smearDown_weights_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(wgamma_scaleUp_weights_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(wgamma_scaleDown_weights_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(wgamma_smearUp_weights_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(wgamma_smearDown_weights_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(zgamma_scaleUp_weights_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(zgamma_scaleDown_weights_pass_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(zgamma_smearUp_weights_pass_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(zgamma_smearDown_weights_pass_total, "dashed", ROOT.kRed, 1)

	GoodPlotFormat(ttbar_scaleUp_weights_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(ttbar_scaleDown_weights_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(ttbar_smearUp_weights_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(ttbar_smearDown_weights_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(sig_scaleUp_weights_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(sig_scaleDown_weights_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(sig_smearUp_weights_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(sig_smearDown_weights_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(wgamma_scaleUp_weights_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(wgamma_scaleDown_weights_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(wgamma_smearUp_weights_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(wgamma_smearDown_weights_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(zgamma_scaleUp_weights_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(zgamma_scaleDown_weights_fail_total, "dashed", ROOT.kRed, 1)
	GoodPlotFormat(zgamma_smearUp_weights_fail_total, "dashed", ROOT.kBlue, 1)
	GoodPlotFormat(zgamma_smearDown_weights_fail_total, "dashed", ROOT.kRed, 1)
	

	
	HVec_pass = [[ttbar_nom_pass_total, ttbar_scaleUp_pass_total, ttbar_scaleDown_pass_total, ttbar_smearUp_pass_total, ttbar_smearDown_pass_total], [sig_nom_pass_total, sig_scaleUp_pass_total, sig_scaleDown_pass_total, sig_smearUp_pass_total, sig_smearDown_pass_total],[wgamma_nom_pass_total, wgamma_scaleUp_pass_total, wgamma_scaleDown_pass_total, wgamma_smearUp_pass_total, wgamma_smearDown_pass_total],[zgamma_nom_pass_total, zgamma_scaleUp_pass_total, zgamma_scaleDown_pass_total, zgamma_smearUp_pass_total, zgamma_smearDown_pass_total]]
	HVec_fail = [[ttbar_nom_fail_total, ttbar_scaleUp_fail_total, ttbar_scaleDown_fail_total, ttbar_smearUp_fail_total, ttbar_smearDown_fail_total], [sig_nom_fail_total, sig_scaleUp_fail_total, sig_scaleDown_fail_total, sig_smearUp_fail_total, sig_smearDown_fail_total],[wgamma_nom_fail_total, wgamma_scaleUp_fail_total, wgamma_scaleDown_fail_total, wgamma_smearUp_fail_total, wgamma_smearDown_fail_total],[zgamma_nom_fail_total, zgamma_scaleUp_fail_total, zgamma_scaleDown_fail_total, zgamma_smearUp_fail_total, zgamma_smearDown_fail_total]]

	for i in range(0,4):
		L = ROOT.TLegend(0.58,0.65,0.895,0.895)
		L.SetFillColor(0)
		L.SetLineColor(0)
		L.AddEntry(HVec_pass[i][0], "Nominal")
		L.AddEntry(HVec_pass[i][1], "ScaleUp")
		L.AddEntry(HVec_pass[i][2], "ScaleDown")
		C = ROOT.TCanvas()
		C.cd()
		HVec_pass[i][0].SetTitle(titles[i]+" Scale Morphing Passing Total")
		HVec_pass[i][0].Draw("hist")
		HVec_pass[i][1].Draw("histsame")
		HVec_pass[i][2].Draw("histsame")
		L.Draw("same")
		AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
		C.Print("morphing/"+save_name[i]+"_pass_scaleMorph_total.png")
		C.Close()
	for i in range(0,4):
		L = ROOT.TLegend(0.58,0.65,0.895,0.895)
		L.SetFillColor(0)
		L.SetLineColor(0)
		L.AddEntry(HVec_pass[i][0], "Nominal")
		L.AddEntry(HVec_pass[i][3], "SmearUp")
		L.AddEntry(HVec_pass[i][4], "SmearDown")
		C = ROOT.TCanvas()
		C.cd()
		HVec_pass[i][0].SetTitle(titles[i]+" Smear Morphing Passing Total")
		HVec_pass[i][0].Draw("hist")
		HVec_pass[i][3].Draw("histsame")
		HVec_pass[i][4].Draw("histsame")
		L.Draw("same")
		AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
		C.Print("morphing/"+save_name[i]+"_pass_smearMorph_total.png")
		C.Close()
	for i in range(0,4):
		L = ROOT.TLegend(0.58,0.65,0.895,0.895)
		L.SetFillColor(0)
		L.SetLineColor(0)
		L.AddEntry(HVec_fail[i][0], "Nominal")
		L.AddEntry(HVec_fail[i][1], "ScaleUp")
		L.AddEntry(HVec_fail[i][2], "ScaleDown")
		C = ROOT.TCanvas()
		C.cd()
		HVec_fail[i][0].SetTitle(titles[i]+" Scale Morphing Failing Total")
		HVec_fail[i][0].Draw("hist")
		HVec_fail[i][1].Draw("histsame")
		HVec_fail[i][2].Draw("histsame")
		L.Draw("same")
		AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
		C.Print("morphing/"+save_name[i]+"_fail_scaleMorph_total.png")
		C.Close()
	for i in range(0,4):
		L = ROOT.TLegend(0.58,0.65,0.895,0.895)
		L.SetFillColor(0)
		L.SetLineColor(0)
		L.AddEntry(HVec_fail[i][0], "Nominal")
		L.AddEntry(HVec_fail[i][3], "SmearUp")
		L.AddEntry(HVec_fail[i][4], "SmearDown")
		C = ROOT.TCanvas()
		C.cd()
		HVec_fail[i][0].SetTitle(titles[i]+" Smear Morphing Failing Total")
		HVec_fail[i][0].Draw("hist")
		HVec_fail[i][3].Draw("histsame")
		HVec_fail[i][4].Draw("histsame")
		L.Draw("same")
		AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
		C.Print("morphing/"+save_name[i]+"_fail_smearMorph_total.png")
		C.Close()

	nom_weights = TLine(0,1,200,1)
	nom_weights.SetLineColor(ROOT.kBlack)
	nom_weights.SetLineStyle(1)

	HVec_weights_pass = [[nom_weights, ttbar_scaleUp_weights_pass_total, ttbar_scaleDown_weights_pass_total, ttbar_smearUp_weights_pass_total, ttbar_smearDown_weights_pass_total], [nom_weights, sig_scaleUp_weights_pass_total, sig_scaleDown_weights_pass_total, sig_smearUp_weights_pass_total, sig_smearDown_weights_pass_total],[nom_weights, wgamma_scaleUp_weights_pass_total, wgamma_scaleDown_weights_pass_total, wgamma_smearUp_weights_pass_total, wgamma_smearDown_weights_pass_total],[nom_weights, zgamma_scaleUp_weights_pass_total, zgamma_scaleDown_weights_pass_total, zgamma_smearUp_weights_pass_total, zgamma_smearDown_weights_pass_total]]
	HVec_weights_fail = [[nom_weights, ttbar_scaleUp_weights_fail_total, ttbar_scaleDown_weights_fail_total, ttbar_smearUp_weights_fail_total, ttbar_smearDown_weights_fail_total], [nom_weights, sig_scaleUp_weights_fail_total, sig_scaleDown_weights_fail_total, sig_smearUp_weights_fail_total, sig_smearDown_weights_fail_total],[nom_weights, wgamma_scaleUp_weights_fail_total, wgamma_scaleDown_weights_fail_total, wgamma_smearUp_weights_fail_total, wgamma_smearDown_weights_fail_total],[nom_weights, zgamma_scaleUp_weights_fail_total, zgamma_scaleDown_weights_fail_total, zgamma_smearUp_weights_fail_total, zgamma_smearDown_weights_fail_total]]

	for i in range(0,4):
		L = ROOT.TLegend(0.58,0.65,0.895,0.895)
		L.SetFillColor(0)
		L.SetLineColor(0)
		L.AddEntry(HVec_weights_pass[i][0], "Nominal Weights")
		L.AddEntry(HVec_weights_pass[i][1], "ScaleUp Weights")
		L.AddEntry(HVec_weights_pass[i][2], "ScaleDown Weights")
		C = ROOT.TCanvas()
		C.cd()
		HVec_weights_pass[i][1].SetTitle(titles[i]+" Scale Morphing Passing Weights Total")
		HVec_weights_pass[i][1].Draw("hist")
		HVec_weights_pass[i][0].Draw("same")
		HVec_weights_pass[i][2].Draw("histsame")
		L.Draw("same")
		AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
		C.Print("morphing/"+save_name[i]+"_pass_scaleMorph_weights_total.png")
		C.Close()
	for i in range(0,4):
		L = ROOT.TLegend(0.58,0.65,0.895,0.895)
		L.SetFillColor(0)
		L.SetLineColor(0)
		L.AddEntry(HVec_weights_pass[i][0], "Nominal Weights")
		L.AddEntry(HVec_weights_pass[i][3], "SmearUp Weights")
		L.AddEntry(HVec_weights_pass[i][4], "SmearDown Weights")
		C = ROOT.TCanvas()
		C.cd()
		HVec_weights_pass[i][3].SetTitle(titles[i]+" Smear Morphing Passing Weights Total")
		HVec_weights_pass[i][3].Draw("hist")
		HVec_weights_pass[i][0].Draw("same")
		HVec_weights_pass[i][4].Draw("histsame")
		L.Draw("same")
		AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
		C.Print("morphing/"+save_name[i]+"_pass_smearMorph_weights_total.png")
		C.Close()
	for i in range(0,4):
		L = ROOT.TLegend(0.58,0.65,0.895,0.895)
		L.SetFillColor(0)
		L.SetLineColor(0)
		L.AddEntry(HVec_weights_fail[i][0], "Nominal Weights")
		L.AddEntry(HVec_weights_fail[i][1], "ScaleUp Weights")
		L.AddEntry(HVec_weights_fail[i][2], "ScaleDown Weights")
		C = ROOT.TCanvas()
		C.cd()
		HVec_weights_fail[i][1].SetTitle(titles[i]+" Scale Morphing Failing Weights Total")
		HVec_weights_fail[i][1].Draw("hist")
		HVec_weights_fail[i][0].Draw("same")
		HVec_weights_fail[i][2].Draw("histsame")
		L.Draw("same")
		AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
		C.Print("morphing/"+save_name[i]+"_fail_scaleMorph_weights_total.png")
		C.Close()
	for i in range(0,4):
		L = ROOT.TLegend(0.58,0.65,0.895,0.895)
		L.SetFillColor(0)
		L.SetLineColor(0)
		L.AddEntry(HVec_weights_fail[i][0], "Nominal Weights")
		L.AddEntry(HVec_weights_fail[i][3], "SmearUp Weights")
		L.AddEntry(HVec_weights_fail[i][4], "SmearDown Weights")
		C = ROOT.TCanvas()
		C.cd()
		HVec_weights_fail[i][3].SetTitle(titles[i]+" Smear Morphing Failing Weights Total")
		HVec_weights_fail[i][3].Draw("hist")
		HVec_weights_fail[i][0].Draw("same")
		HVec_weights_fail[i][4].Draw("histsame")
		L.Draw("same")
		AddCMSLumi(ROOT.gPad, LUMI, cmsextra)
		C.Print("morphing/"+save_name[i]+"_fail_smearMorph_weights_total.png")
		C.Close()


